version: '2'
services:
  fishproject:
    image: ghcr.io/anoniemebeer/fishtankprojectiot:1
    container_name: fishproject
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Brussels
      - PGID=1000
      - PUID=1000
    privileged: true
